---
title: "YAŞAM MEMNUNİYETİNİ ETKİLEYEN FAKTÖRLERİN TÜRKİYEDEKİ İLLER ÖRNEĞİ ÜZERİNDEN İNCELENMESİ-GELİR ETKİSİ"
author: 
  - Alper Helik[^1]
bibliography: ../bibliography/biblio.bib
csl: ../csl/apa-tr.csl
header-includes:
  - \usepackage{polyglossia}
  - \setmainlanguage{turkish}
  - \usepackage{booktabs}
  - \usepackage{caption} 
  - \captionsetup[table]{skip=10pt}
output:
  bookdown::pdf_document2:
    fig_caption: yes
    fig_height: 3
    fig_width: 4
    keep_tex: no
    latex_engine: xelatex
    number_sections: yes
    toc: no
geometry: margin=1in
link-citations: yes
urlcolor: blue
fontsize: 12pt
biblio-style: apalike
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(cache = FALSE, echo = TRUE, message = FALSE, warning = FALSE)
```

<!-- ======================================================================= -->
<!-- ============================== NOTLAR ================================= -->
<!-- ======================================================================= -->
[^1]: 19080220, [Github Repo](https://github.com/alperhelik/arasinav_19080220)



# Giriş
Aynı zamanda yaşam doyumu olarak adlandırabileceğimiz yaşam memnuniyeti, (bireyin hayattan ne derecede memnun olduğunun, yaşamından ne kadar hoşlandığının önemli bir göstergesi olarak kabul edilebilir.) Elbette bireylerin yaşam doyumu üzerinde etkiye sahip birçok sayıda değişken vardır. Gelir, sağlık, güvenlik, barınma, eğitim gibi faktörler her bireyin temel ihtiyacı olup mutluluk düzeyleri üzerinde kuşkusuz önemli yerlere sahiptir. Ele alacağımız çalışmanın amacı ise daha önce de değindiğimiz gibi Türkiye İstatistik Kurumundan edindiğimiz 2015 yılına ait 81 gözlem ve 40’ı aşkın değişkene sahip verilerle ülkemizdeki popülasyonların mutluluk düzeylerini etkileyen değişkenlerden gelirin, çeşitli istatistiksel çalışmalarla ne oranda önem arz ettiğini incelemek olacak. (Çalışma neticesinde, bireyin yaşı, cinsiyeti, medeni durumu, eğitim durumu, çalışma durumu, gelir düzeyinden memnuniyeti, sağlığından memnuniyet, aldığı eğitimden memnuniyet, sosyal hayatından memnuniyet, asayiş hizmetlerinden memnuniyet ve sosyal güvenlik kurumu hizmetlerinden memnuniyet faktörlerinin yaşam memnuniyeti üzerinde etkili olduğu tespit edilmiştir.) KARACAASLAN’ın 2021 yılında bireyler üzerinden edindiği istatistiksel verilerle vardığı bu sonuç çalışmamızda yer verdiğimiz değişkenlerin doğruluğunu ve ehemmiyetini kanıtlar niteliktedir.


## Çalışmanın Amacı
Bu çalışmada TUİK’ in 2015 yılına ait illere göre yaşam endeksi verisi kullanılarak, Türkiye örneği üzerinde yaşam memnuniyetini etkileyen değişkenler arasından, gelirin mutluluk düzeyi üzerine nihai etkisini inceleyeceğiz. Yaşam memnuniyeti üzerine yapılan daha önceki çalışmalardan ortaya çıkan sonuca göre birçok değişken yaşam memnuniyeti üzerinde önem arz etmektedir. Yapacağım çalışmada gelirin ve mutluluk düzeyinin Türkiye üzerindeki iller üzerinden incelemesini ele alacağız, bölgeler arası kişi başına düşen tasarruf mevduatı miktarı, orta ve üst gelir grubundaki hane halkının oranı, temel ihtiyaçlara ulaşım noktasında sıkıntı çeken hanelerin oranı gibi değişkenleri diğer değişkenlerde nispeten göz önünde bulundurularak coğrafi bölgeler üzerindeki ortalamaları ve bölgelere ait illerin genel mutluluk düzeylerinin ortalama gözlemleri sonucunda gelirin mutluluk düzeyi üzerine etkisini bölgesel bazda ele almış olacağız. Araştırmada cevabı aranacak sorular şunlardır;
1)Temel ihtiyaçlara ulaşılabilirlik ve gelir düzeyinin mutluluk düzeyi ile ilişkisinin bölgesel olarak dağlımı?
2)Bölgesel olarak gelir ve mutluluk düzeyi dağılımının illerin gelir ve mutluluk düzeyi ilişkileri ile farklılıkları?
3)Mutluluk düzeyinin belirlenmesinde gelirin etkisi?
Çalışmamız boyunca elimizdeki istatiksel verileri kullanarak yukardaki sorulara cevap arayacağız ve bulduğumuz cevaplar neticesinde gelirin mutluluk düzeyi üzerine etkisini bölgelere göre sıralayarak incelemede bulunacağız. Analizimin sonucunda nihai olarak tüm insanlığın arayışında olduğu mutluluk düzeyinin gelir düzeyi ile ilişkisini toplumun geniş bir kitlesi üzerinden inceleyerek ne denli bir etkiye sahip olduğu veya olmadığı hakkında fikir sahip olacağız.


## Literatür 
Guoqiang TIAN ve Liyan YANG’ın çalışmalarına göre (Eastlerin paradoksunu inceleyin- hayatlarımızda bir bulmaca “gelirin mutluluk düzeyine etkisi? “. Ortalama mutluluk seviyeleri
Ülkeler zenginleştikçe artmaz. Bu teori, çalışmak için bizlere bir temel oluşturur.
Sosyal mutluluğu en üst düzeye çıkarmak ve bireylerin mutluluk düzeyini en üst düzeye çıkarmaya bağlıdır bu durum ise bireysel faydaya dayanır. Hem maddi malları hem de maddi olmayan malları dikkatle incelediğimizde ve bütünsel olarak göz önüne aldığımızda. Mevcut referans grubu teorisi ve” ihmal edilen değişkenler" teorisi Bireysel ve sosyal refah / mutluluk arasındaki temel çatışmaya dayanır. Maddi olmayan durumla olumlu ilişkili kritik bir gelir seviyesi vardır ve gelir düzeyindeki artış mutluluğu doğrudan arttırır. Kritik gelir seviyesine ulaşıldığında ise gelirdeki artış mutluluk düzeyinde artışa sebep olmaz
Ve aslında biraz şaşırtıcı, ortalama mutluluk aslında kritik gelir seviyesinin aşılmasının ardından azalır, bu da Pareto verimsiz sonuçlara neden olur.) Teoriden çıkan sonucun politik olarak anlamı şudur: Bir hükümet maddi ve maddi olmayan malları dengeli bir şekilde teşvik etmelidir. Sonuç alarak YANG ve TIAN’ın araştırmaları ve gözlemlerinin sonucu olarak varacağımız sonuç gelirin mutluluk düzeyi üzerine etkisinin Eastlerin paradoksuna ve kritik bir gelir düzeyine bağlı olduğu sonucudur çalışmamızda bölgelerin gelir düzeylerinin bu paradoksa paralelliği noktasında çalışmamıza fayda sağlayabileceği düşüncesindeyim.  Veenhoven, R. (1996) yılındaki çalışmasında gelir ve mutluluk düzeyi üzerine etkisini gelir dağılımındaki adaletsizliğe dayandırarak şu şekilde ifade ediyor: (Parasal kazançlar, gelir güvenliği (varlıkları koruyan kanun ve yasalar) ve gelir eşitliği derecesi gibi faktörleri irdeleyerek bugün hala önemli olan yoksulluk ve sosyal eşitsizliğin mutluluk üzerine etkisini tartışma konusu olarak işliyor.) Gelirin mutluluk düzeyine etkisinin yanında diğer değişkenlere de Türkiye özelinde değerlendiren KARAASLAN ise gelirden ziyade kamu kaynaklarına ve sağlığa erişimin yaşam doyumu üzerine etkisinin ülkemiz genelinde en önemli faktör olduğunu şu şekilde ifade ediyor; (Türkiye’de yaşam memnuniyetini etkileyen en önemli faktör sağlık olarak bulunmuştur. Sağlık hizmetleri başta olmak üzere kamu hizmetleri de yine yaşam memnuniyetini belirleyen önemli faktörler olarak tespit edilmiştir.) fakat bunun yanında KARAASLAN çalışmasında referans aldığı popülasyonda (Gelir düzeyinden çok memnun olan bireyin referans gruba göre
yaşamından ne memnun ne memnun olmama olasılığı %36,2 daha az iken
yaşamından çok memnun olma olasılığı %102,5 daha fazladır) değerlendirmesiyle gelir etkisinin mutluluk düzeyine etkisinin yadsınamaz ve incelemeye değer olduğunu bizlere gösteriyor. KAHYAOGLU’nun gelir ve mutluluk düzeyi üzerine Türkiyedeki incelemeside çalışmamızı destekler ve incelemeye değer nitelikte. KAHYAOGLU ise yaptığı 6714 gözlemli anket çalışmasının sonucunda vardığı şu sonuçta gelirin mutluluk düzeyine etkisi üzerine ele alacağımız çalışmada bizi destekler niteliktedir. (r. Buradan elde
edilen sonuç ile yaşam memnuniyeti araştırmasındaki sonuç yine benzer bir nitelik
göstermektedir. Son olarak, aylık harcama miktarı ile finansal durum arasındaki
ilişki, maddi durumu iyi olup yüksek harcamalarda bulunan öğrencilerin yaşam
memnuniyetlerinin daha yüksek olduğunu sonucu elde edilmiştir. Üzerinde çalışılan
yaşam memnuniyeti araştırmasında da gelir düzeyi yükseldikçe bireylerin yaşam
memnuniyetlerinin arttığı sonucu bulunmuştur.) 



\newpage
# Kaynakça {#references}
<div id="refs"></div>

